### ISSUE TITLE
X and Y offset?

### ISSUE THREAD

**Issue by PeteMichaud** [matthewarcus/mmps#3]
Hey again Matt!

Since last we spoke in the previous issue, I've ported MMPS to C# .NET: https://github.com/PeteMichaud/MapProjectorStudio

I'm in the process of adding a bunch of features, but first I've been refactoring and writing comprehensive tests and docs.

In the process of testing I've found that the `xoff` and `yoff` parameters are broken. Specifying any(?) value causes the output to be blank. 

I thought it was my code at first, but then I checked the same settings against my build of mmps, and found the same result. 

The problem is that I'm not exactly sure what the intended behavior is, so I can't fix it. Is it just left over from a time before the -lat and -lon parameters were implemented? Should they simply be removed?

**Comment by matthewarcus** [comment]
Nice work! I haven't done anything on MMPS for a while (and it's about 20
years since I wrote most of the code) - glad you (and hopefully others) are
finding it useful.

I'll have a look at xoff and yoff and see if I can remember what they were
supposed to do.

BTW, your github page has me as "Mattew Warcus" - it's "Matthew Arcus" of
course.

All the best,

Matthew.

**Comment by matthewarcus** [comment]
Another thing - I see you've gone for GPL for your project (since I
did). I'm quite inclined to change to the MIT though (I certainly
would if it was a new project) - would you prefer that?

Matthew.

**Comment by matthewarcus** [comment]
Looks like xoff and yoff apply an offset to the image itself, with units
depending on the type of image being displayed, eg. the "make test" target,
with the perspective mapping, xoff and yoff are in the range (-2,2), eg. if
we change to:

./project perspective -xoff 1 -yoff 1 -lat 20 -long 30 -x 6 -sun -date 172
-time 3.83 -f images/earth.ppm | display

I get the attached image - for "cylindrical" type mappings, the x dimension
is [-3.14,3.14], not sure about y, depends on the projection I think.

**Comment by PeteMichaud** [comment]
> I see you've gone for GPL for your project (since I did). I'm quite inclined to change to the MIT though (I certainly would if it was a new project) - would you prefer that? 

Certainly! I didn't want to presume :)

Sorry about the name typo, I'll fix it shortly.

**Comment by matthewarcus** [comment]
Moved to MIT license...

**Comment by PeteMichaud** [comment]
I updated the tests and notes on `xoff` and `yoff` thanks for the help!
